# Generated by Django 6.0.2 on 2026-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogcategory_blogtag_developerstat_experienceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='database_used',
            field=models.CharField(blank=True, default='PostgreSQL', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_stack',
            field=models.CharField(blank=True, default='Railway, Vercel', max_length=140),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshots_gallery',
            field=models.TextField(blank=True, help_text='Comma-separated screenshot URLs for gallery placeholders.'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_cta',
            field=models.CharField(default='Get practical full stack, AI, and SEO learning insights in your inbox.', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Full Stack Engineer | AI Developer | Technical Writer | SEO Learner', max_length=160),
        ),
    ]
