# Generated by Django 6.0.2 on 2026-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_api_count_project_architecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
