# Generated by Django 6.0.2 on 2026-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_attachment_sitesettings_twitter_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceitem',
            name='item_type',
            field=models.CharField(choices=[('education', 'Education'), ('internship', 'Internship'), ('employment', 'Professional Experience'), ('freelance', 'Freelance'), ('project', 'Project'), ('learning', 'Learning Journey'), ('certification', 'Certification')], default='project', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_email',
            field=models.EmailField(default='muhammedsiddique240@gmail.com', max_length=254),
        ),
    ]
