# Generated by Django 6.0.2 on 2026-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_experience_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Project category e.g. SaaS ERP', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshots_gallery',
            field=models.TextField(blank=True, help_text='Primary static image filename (e.g. duality_hotel_pool.jpg) or comma-separated list.'),
        ),
    ]
